### ISSUE TITLE
Add library

### ISSUE THREAD

**Issue by umairidris** [apparentlymart/terraform-clean-syntax#12]
Hi @apparentlymart,

First thanks for this useful binary. I would like to leverage go modules to incorporate it into our go code so we don't need to ask users to compile the binary and pass a filepath to us. Would you be open to accepting a PR that pulls the code into a library and making a release for it?

Thanks!

**Comment by apparentlymart** [comment]
Hi @umairidris,

I intended this as a one-off little project to address an immediate concern, and so I'm not intending to make any further changes to it or support it as a library. I've you'd like to use what I wrote here as a basis of your own library, though, I have no objection!

**Comment by umairidris** [comment]
Sounds good, thanks!
